### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by louanfontenele** [finallion/The-Graveyard-FORGE-#3]
Hello everyone, my server is crashing : https://pastebin.com/U751dhJ7
```console
[15:32:50 FATAL]: Mixin apply failed graveyard.mixins.json:ServerPlayNetworkHandlerMixin -> net.minecraft.network.play.ServerPlayNetHandler: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on signUpdate could not find any targets matching 'Lnet/minecraft/network/play/ServerPlayNetHandler;func_244542_a(Lnet/minecraft/network/play/client/CUpdateSignPacket;Ljava/util/List;)V' in net.minecraft.network.play.ServerPlayNetHandler. Using refmap graveyard.refmap.json [PREINJECT Applicator Phase -> graveyard.mixins.json:ServerPlayNetworkHandlerMixin -> Prepare Injections ->  -> handler$zhp000$signUpdate(Lnet/minecraft/network/play/client/CUpdateSignPacket;Ljava/util/List;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on signUpdate could not find any targets matching 'Lnet/minecraft/network/play/ServerPlayNetHandler;func_244542_a(Lnet/minecraft/network/play/client/CUpdateSignPacket;Ljava/util/List;)V' in net.minecraft.network.play.ServerPlayNetHandler. Using refmap graveyard.refmap.json [PREINJECT Applicator Phase -> graveyard.mixins.json:ServerPlayNetworkHandlerMixin -> Prepare Injections ->  -> handler$zhp000$signUpdate(Lnet/minecraft/network/play/client/CUpdateSignPacket;Ljava/util/List;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at jdk.internal.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:241) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:32:50 ERROR]: Encountered an unexpected exception
[15:32:50 ERROR]:       Cause of unexpected exception was
[15:32:50 FATAL]: Preparing crash report with UUID
```
how can i fix it?

**Comment by finallion** [comment]
Which version of the mod and forge are you using? And when did the crash happen? Right at the start?

**Comment by finallion** [comment]
I'm closing this. If this issue happens again, feel free to reopen it.
